'use client';
import Link from 'next/link';
import Image from 'next/image';
import { motion } from 'motion/react';
import { ShoppingCart, ArrowUpRight } from 'lucide-react';
import { Badge } from '@/components/ui/Badge';
import { money } from '@/lib/utils';
import type { Product } from '@/types';
import { useCartStore } from '@/stores/cart';
import { toast } from 'sonner';
export function ProductCard({product}:{product:Product}){const add=useCartStore(s=>s.add); return <motion.div whileHover={{y:-5,rotateX:1,rotateY:-1}} transition={{type:'spring',stiffness:260,damping:18}} className="group rounded-2xl"><div className="relative overflow-hidden rounded-2xl border border-white/10 bg-white/[0.045] shadow-black/20 transition group-hover:border-fuchsia-300/20 group-hover:shadow-neon"><div className="relative aspect-[4/3] overflow-hidden bg-black/20">{product.thumbnail?<Image src={product.thumbnail} alt={product.name} fill className="object-cover transition duration-500 group-hover:scale-105" sizes="(max-width:768px) 100vw, 25vw"/>:<div className="grid h-full place-items-center bg-linear-to-br from-violet-950 via-fuchsia-950 to-cyan-950 text-4xl font-black text-white/20">LV</div>}<div className="absolute left-3 top-3 flex gap-2">{product.featured&&<Badge>HOT</Badge>}{product.discount>0&&<Badge tone="pink">-{product.discount}%</Badge>}</div></div><div className="p-4"><div className="mb-2 flex items-center justify-between gap-2"><Badge tone={product.category==='acc'?'cyan':'violet'}>{product.category.toUpperCase()}</Badge><span className="text-xs text-white/35">Đã bán {product.soldCount}</span></div><Link href={`/product/${product.slug}`} className="line-clamp-2 font-semibold text-white hover:text-cyan-200">{product.name}</Link><div className="mt-3 flex items-end justify-between gap-3"><div><div className="text-lg font-black text-white">{money(product.price)}</div>{product.originalPrice>product.price&&<div className="text-xs text-white/35 line-through">{money(product.originalPrice)}</div>}</div><div className="flex gap-2"><Link href={`/product/${product.slug}`} className="grid h-10 w-10 place-items-center rounded-xl border border-white/10 bg-white/5 text-white/70 hover:text-white"><ArrowUpRight className="h-4 w-4"/></Link><button onClick={()=>{add({productId:product.id,quantity:1});toast.success('Đã thêm vào giỏ hàng.')}} className="grid h-10 w-10 place-items-center rounded-xl bg-linear-to-br from-fuchsia-500 to-violet-500 text-white shadow-neon"><ShoppingCart className="h-4 w-4"/></button></div></div></div></div></motion.div>}
