'use client';
import { useState } from 'react';
import { createUserWithEmailAndPassword, sendPasswordResetEmail, signInWithEmailAndPassword, signInWithPopup, updateProfile } from 'firebase/auth';
import { auth, googleProvider } from '@/firebase/client';
import { Button } from '@/components/ui/Button';
import { Input } from '@/components/ui/Input';
import { toast } from 'sonner';
import { useRouter } from 'next/navigation';
import Link from 'next/link';
import { Eye, EyeOff, Chrome } from 'lucide-react';
import { z } from 'zod';
const loginSchema=z.object({email:z.email(),password:z.string().min(6)});
const registerSchema=z.object({username:z.string().min(3).max(32),email:z.email(),password:z.string().min(6),confirm:z.string().min(6)}).refine(v=>v.password===v.confirm,{path:['confirm'],message:'Mật khẩu xác nhận không khớp.'});
export function LoginForm(){const router=useRouter();const [busy,setBusy]=useState(false);const [show,setShow]=useState(false);async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);try{const f=new FormData(e.currentTarget);const v=loginSchema.parse({email:String(f.get('email')),password:String(f.get('password'))});await signInWithEmailAndPassword(auth,v.email,v.password);toast.success('Đăng nhập thành công.');router.push('/profile')}catch(e){toast.error(e instanceof Error?e.message:'Không thể đăng nhập.')}finally{setBusy(false)}}async function google(){setBusy(true);try{await signInWithPopup(auth,googleProvider);toast.success('Đăng nhập Google thành công.');router.push('/profile')}catch(e){toast.error(e instanceof Error?e.message:'Không thể đăng nhập Google.')}finally{setBusy(false)}}return <div className="space-y-4"><form onSubmit={submit} className="space-y-4"><Input name="email" type="email" label="Email" required/><label className="block space-y-2"><span className="text-sm font-medium text-white/75">Mật khẩu</span><div className="relative"><input name="password" type={show?'text':'password'} minLength={6} required className="w-full rounded-xl border border-white/10 bg-black/20 px-3.5 py-3 pr-11 text-sm text-white outline-none focus:border-fuchsia-400/60"/><button type="button" onClick={()=>setShow(!show)} className="absolute right-3 top-1/2 -translate-y-1/2 text-white/40">{show?<EyeOff/>:<Eye/>}</button></div></label><div className="flex justify-end"><Link href="/forgot-password" className="text-xs text-white/45 hover:text-white">Quên mật khẩu?</Link></div><Button className="w-full" loading={busy}>Đăng nhập</Button></form><div className="flex items-center gap-3 text-xs text-white/30"><div className="h-px flex-1 bg-white/10"/>hoặc<div className="h-px flex-1 bg-white/10"/></div><Button variant="secondary" className="w-full" onClick={google} loading={busy}><Chrome className="h-4 w-4"/>Tiếp tục với Google</Button></div>}
export function RegisterForm(){const router=useRouter();const [busy,setBusy]=useState(false);const [show,setShow]=useState(false);async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);try{const f=new FormData(e.currentTarget);const v=registerSchema.parse({username:String(f.get('username')),email:String(f.get('email')),password:String(f.get('password')),confirm:String(f.get('confirm'))});const cred=await createUserWithEmailAndPassword(auth,v.email,v.password);await updateProfile(cred.user,{displayName:v.username});const token=await cred.user.getIdToken();await fetch('/api/users/bootstrap',{method:'POST',headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json'}});toast.success('Tạo tài khoản thành công.');router.push('/profile')}catch(e){toast.error(e instanceof Error?e.message:'Không thể đăng ký.')}finally{setBusy(false)}}return <form onSubmit={submit} className="space-y-4"><Input name="username" label="Username" minLength={3} maxLength={32} required/><Input name="email" type="email" label="Email" required/><label className="block space-y-2"><span className="text-sm font-medium text-white/75">Mật khẩu</span><div className="relative"><input name="password" type={show?'text':'password'} minLength={6} required className="w-full rounded-xl border border-white/10 bg-black/20 px-3.5 py-3 pr-11 text-sm text-white outline-none focus:border-fuchsia-400/60"/><button type="button" onClick={()=>setShow(!show)} className="absolute right-3 top-1/2 -translate-y-1/2 text-white/40">{show?<EyeOff/>:<Eye/>}</button></div></label><Input name="confirm" type={show?'text':'password'} label="Xác nhận mật khẩu" minLength={6} required/><div className="rounded-xl border border-cyan-300/10 bg-cyan-300/5 p-3 text-xs text-white/45">Mật khẩu tối thiểu 6 ký tự. Password không được lưu vào Firestore.</div><Button className="w-full" loading={busy}>Tạo tài khoản</Button></form>}
export function ForgotPasswordForm(){const [busy,setBusy]=useState(false);return <form onSubmit={async(e)=>{e.preventDefault();setBusy(true);try{const email=String(new FormData(e.currentTarget).get('email'));if(!z.email().safeParse(email).success) throw new Error('Email không hợp lệ.');await sendPasswordResetEmail(auth,email);toast.success('Đã gửi email đặt lại mật khẩu.');}catch(e){toast.error(e instanceof Error?e.message:'Không thể gửi email.')}finally{setBusy(false)}}} className="space-y-4"><Input name="email" type="email" label="Email" required/><Button className="w-full" loading={busy}>Gửi liên kết reset</Button></form>}
