"use client";
import {useEffect,useMemo,useState} from 'react';
import {api} from '@/lib/client/api';
import {Card} from '@/components/ui/Card';
import {Button} from '@/components/ui/Button';
import {Input} from '@/components/ui/Input';
import {toast} from 'sonner';

type Row={id:string;username:string;note:string;status:string;createdAt:unknown};
export default function InventoryAdmin(){
 const [products,setProducts]=useState<any[]>([]); const [productId,setProductId]=useState(''); const [bulk,setBulk]=useState(''); const [rows,setRows]=useState<Row[]>([]); const [q,setQ]=useState(''); const [status,setStatus]=useState(''); const [busy,setBusy]=useState<string|null>(null);
 useEffect(()=>{api<any[]>('/api/admin/products').then(setProducts).catch(()=>setProducts([]))},[]);
 async function load(){if(!productId){setRows([]);return}try{setRows(await api<Row[]>(`/api/admin/inventory?productId=${encodeURIComponent(productId)}${status?`&status=${status}`:''}${q?`&q=${encodeURIComponent(q)}`:''}`))}catch(e){toast.error(e instanceof Error?e.message:'Không tải inventory.')}}
 useEffect(()=>{const t=setTimeout(load,250);return()=>clearTimeout(t)},[productId,status,q]);
 async function importRows(){try{const r=await api<any>('/api/admin/inventory',{method:'POST',body:JSON.stringify({productId,bulk})});toast.success(`Đã import ${r.count} ACC.`);setBulk('');await load()}catch(e){toast.error(e instanceof Error?e.message:'Không import được.')}}
 async function remove(id:string){if(busy||!window.confirm('Xóa ACC chưa bán này?'))return;setBusy(id);try{await api('/api/admin/inventory',{method:'DELETE',body:JSON.stringify({productId,itemId:id})});toast.success('Đã xóa inventory item.');await load()}catch(e){toast.error(e instanceof Error?e.message:'Không xóa được.')}finally{setBusy(null)}}
 const available=useMemo(()=>rows.filter(r=>r.status==='available').length,[rows]);
 return <div><h1 className="text-3xl font-black">ACC Inventory</h1><Card className="mt-6 p-5"><label className="space-y-2"><span className="text-sm text-white/70">Sản phẩm ACC</span><select value={productId} onChange={e=>setProductId(e.target.value)} className="w-full rounded-xl border border-white/10 bg-black/20 px-3 py-3"><option value="">Chọn product…</option>{products.filter(p=>p.category==='acc').map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label className="mt-4 block space-y-2"><span className="text-sm text-white/70">Bulk paste — username|password|note</span><textarea value={bulk} onChange={e=>setBulk(e.target.value)} className="min-h-52 w-full rounded-xl border border-white/10 bg-black/20 p-3 font-mono text-sm outline-none"/></label><div className="mt-2 text-xs text-white/35">Credentials được mã hóa trước khi lưu và chỉ username/note đã giải mã được hiển thị trong admin.</div><Button className="mt-4" onClick={importRows} disabled={!productId||!bulk.trim()}>Import</Button></Card>{productId&&<Card className="mt-6 p-5"><div className="flex flex-wrap items-end gap-3"><div className="min-w-56 flex-1"><Input label="Tìm username/note" value={q} onChange={e=>setQ(e.target.value)} /></div><label className="min-w-40 space-y-2"><span className="text-sm text-white/70">Status</span><select value={status} onChange={e=>setStatus(e.target.value)} className="w-full rounded-xl border border-white/10 bg-black/20 px-3 py-3"><option value="">Tất cả</option><option value="available">Available</option><option value="sold">Sold</option></select></label><div className="pb-2 text-sm text-white/45">Available: {available}</div></div><div className="mt-5 overflow-x-auto"><table className="min-w-full text-sm"><thead className="bg-white/5"><tr><th className="px-3 py-2 text-left">Username</th><th className="px-3 py-2 text-left">Note</th><th className="px-3 py-2 text-left">Status</th><th className="px-3 py-2 text-left">Action</th></tr></thead><tbody className="divide-y divide-white/8">{rows.map(r=><tr key={r.id}><td className="px-3 py-2 font-mono">{r.username}</td><td className="px-3 py-2 text-white/45">{r.note||'—'}</td><td className="px-3 py-2">{r.status}</td><td className="px-3 py-2">{r.status==='available'&&<Button variant="danger" onClick={()=>remove(r.id)} loading={busy===r.id}>Xóa</Button>}</td></tr>)}</tbody></table></div></Card>}</div>
}
